# Common US Craigslist market subdomains, grouped by region.
# The value is the subdomain used in https://<subdomain>.craigslist.org
MARKETS = [
    # Northeast
    ("boston", "Boston, MA"),
    ("newyork", "New York, NY"),
    ("philadelphia", "Philadelphia, PA"),
    ("washingtondc", "Washington, DC"),
    ("baltimore", "Baltimore, MD"),
    ("hartford", "Hartford, CT"),
    ("providence", "Providence, RI"),
    # Southeast
    ("atlanta", "Atlanta, GA"),
    ("miami", "Miami, FL"),
    ("orlando", "Orlando, FL"),
    ("tampa", "Tampa, FL"),
    ("raleigh", "Raleigh, NC"),
    ("charlotte", "Charlotte, NC"),
    ("nashville", "Nashville, TN"),
    ("memphis", "Memphis, TN"),
    ("neworleans", "New Orleans, LA"),
    ("jacksonville", "Jacksonville, FL"),
    # Midwest
    ("chicago", "Chicago, IL"),
    ("detroit", "Detroit, MI"),
    ("cleveland", "Cleveland, OH"),
    ("columbus", "Columbus, OH"),
    ("minneapolis", "Minneapolis, MN"),
    ("milwaukee", "Milwaukee, WI"),
    ("indianapolis", "Indianapolis, IN"),
    ("stlouis", "St. Louis, MO"),
    ("kansascity", "Kansas City, MO"),
    ("omaha", "Omaha, NE"),
    # Southwest
    ("dallas", "Dallas, TX"),
    ("houston", "Houston, TX"),
    ("austin", "Austin, TX"),
    ("sanantonio", "San Antonio, TX"),
    ("phoenix", "Phoenix, AZ"),
    ("tucson", "Tucson, AZ"),
    ("albuquerque", "Albuquerque, NM"),
    ("lasvegas", "Las Vegas, NV"),
    # West
    ("losangeles", "Los Angeles, CA"),
    ("sfbay", "San Francisco Bay Area, CA"),
    ("sandiego", "San Diego, CA"),
    ("sacramento", "Sacramento, CA"),
    ("fresno", "Fresno, CA"),
    ("portland", "Portland, OR"),
    ("seattle", "Seattle, WA"),
    ("spokane", "Spokane, WA"),
    ("saltlakecity", "Salt Lake City, UT"),
    ("denver", "Denver, CO"),
    ("anchorage", "Anchorage, AK"),
    ("honolulu", "Honolulu, HI"),
]
